<?php
/**
 * @file dumper.module
 *
 * Module to help dump and restore OG content.
 *
 * @TODO: Autoloader callback.
 * @TODO: Drush command to dump an og
 *  drush dumper_backup %nid %date
 * @TODO: Drush command to restore an og
 *  drush dumper_restore %nid %date
 * @TODO: Implements hook og menu-item.
 * @TODO: Implements hook og permission.
 * @TODO: Save entity path if supported.
 * @TODO: Replace school with og-node.
 */

spl_autoload_register('dumper_autoload');

/**
 * Autoloeader.
 */
function dumper_autoload($class) {
  $do = strpos($class, 'Dumper_') === 0;
  $do = $do || strpos($class, 'Restorer_') === 0;
  if ($do) {
    $file = dirname(__FILE__) . '/lib/' . str_replace('_', '/', $class) . '.php';

    if (file_exists($file)) {
      require_once $file;
    }
    else {
      drush_print_r("Fail on loading {$class}. File is not existing: {$file}");
      drush_print_r(debug_backtrace());
      throw new Exception("Autoload fails: {$class}");
    }
  }
}

/**
 * Implements hook_permission().
 */
function dumper_permission() {
  return array(
    'dumper backup' => array(
      'title' => 'Backup OG content',
      'description' => '',
    ),
    'dumper restore' => array(
      'title' => 'Restore OG content',
      'description' => '',
    ),
  );
}

# Implements hook_menu().
# function dumper_menu() {}
