<?php
/**
 * @file dumper.module
 *
 * Module to help dump and restore OG content.
 *
 * @TODO: Implements hook og menu-item.
 * @TODO: Implements hook og permission.
 * @TODO: Save entity path if supported.
 */

/**
 * Register our auto loader
 */
spl_autoload_register('dumper_autoload');

/**
 * Autoloeader.
 */
function dumper_autoload($class) {
  $do = strpos($class, 'Dumper_') === 0;
  $do = $do || strpos($class, 'Restorer_') === 0;
  if (!$do) return;

  if (!file_exists($file = dirname(__FILE__) . '/lib/' . str_replace('_', '/', $class) . '.php')) {
    throw new Exception("Autoload fails: {$class}");
  }

  require_once $file;
}

/**
 * Implements hook_permission().
 */
function dumper_permission() {
  return array(
    'dumper backup' => array(
      'title' => 'Backup OG content',
      'description' => '',
    ),
    'dumper restore' => array(
      'title' => 'Restore OG content',
      'description' => '',
    ),
  );
}

# Implements hook_menu().
# function dumper_menu() {}
